# travis ci
os: linux
dist: xenial
language: node_js

node_js:
  - '8'
  - '10'
  - '12'
before_script:
  - sudo apt-get install -qq -y xsltproc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - npm install
script:
  - true
